config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'notices#index'
  resources :notices do
    resources :comments, :controller => 'notice_comments'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :notices
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :notice
  belongs_to :user
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notices, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notice_comments_controller.rb
class NoticeCommentsController < ApplicationController
  before_action :find_notice

  def index
    @comments = @notice.comments
  end

  def show
    @comment = @notice.comments.find( params[:id] )
  end

  def new
    @comment = @notice.comments.build
  end

  def create
    @comment = @notice.comments.build( comment_params )
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to notice_comments_url( @notice )
    else
      render :action => :new
    end
  end

  def edit
    @comment = @notice.comments.find( params[:id] )
  end

  def update
    @comment = @notice.comments.find( params[:id] )

    if @comment.update( comment_params )
      redirect_to notice_comments_url( @notice )
    else
      render :action => :edit
    end

  end

  def destroy
    @comment = @notice.comments.find( params[:id] )
    @comment.destroy

    redirect_to notice_comments_url( @notice )
  end

  protected

  def find_notice
    @notice = Notice.find( params[:notice_id] )
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = current_user.notices.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = current_user.notices.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :content, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notice_comments_helper.rb
module NoticeCommentsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emercency Notice Board</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
  <%= "#{current_user.email}" %> |
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
  <%= link_to('註冊', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

app/views/notice_comments/edit.html.erb
<%= form_for @comment, :url => notice_comment_path(@notice, @comment), :html => { :method => :patch } do |f| %>
   <%= f.text_field :content %>
   <%= f.submit %>
<% end %>

app/views/notice_comments/index.html.erb
<p />
<table>
  <thead>
    <tr>
      <td>Comment</td>
      <td>User</td>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
      <td><%= comment.user.email %></td>
      <% if comment.user == current_user %>
      <td><%= link_to 'Edit', edit_notice_comment_path(@notice, comment) %></td>
      <td><%= link_to 'Destroy', notice_comment_path(@notice, comment), :method => :delete %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New comment', new_notice_comment_path(@notice) %>
<%= link_to 'All notices', notices_path %>

app/views/notice_comments/new.html.erb
<%= form_for @comment, :url => notice_comments_path(@notice) do |f| %>
<%= f.text_field :content %>
<%= f.submit %>
<% end %>

app/views/notice_comments/show.html.erb
<p><%= @comment.content %></p>

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="category">
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<h1>Emergency Notices</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Posted By</th>
      <th>Last Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.category.name %></td>
        <td><%= notice.title %></td>
        <td><%= notice.user.email %></td>
        <td><%= notice.updated_at %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Comments', notice_comments_path(notice) %></td>
        <% if notice.user == current_user %>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @notice.category.name %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>